include: package:flutter_lints/flutter.yaml

analyzer:
  errors:
    invalid_annotation_target: ignore

linter:
  rules:
    avoid_print: true
    prefer_const_constructors: true
    prefer_final_locals: true
